name: algo_ops_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - 'black[jupyter]'
    - bleach==6.0.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docutils==0.19
    - executing==1.2.0
    - ezplotly
    - fastjsonschema==2.16.3
    - fonttools==4.39.2
    - fqdn==1.5.1
    - idna==3.4
    - importlib-metadata==6.0.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jaraco-classes==3.2.3
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kaleido==0.2.1
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.5
    - more-itertools==9.1.0
    - mypy-extensions==1.0.0
    - natsort==8.3.1
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - nose
    - nose2
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.24.2
    - opencv-python-headless==4.7.0.72
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.11.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkginfo==1.9.6
    - platformdirs==3.1.1
    - plotly==5.13.1
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.1
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - readme-renderer==37.3
    - requests==2.28.2
    - requests-toolbelt==0.10.1
    - rfc3339-validator==0.1.4
    - rfc3986==2.0.0
    - rfc3986-validator==0.1.1
    - rich==13.3.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tenacity==8.2.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenize-rt==5.0.0
    - tomli==2.0.1
    - tornado==6.2
    - traitlets==5.9.0
    - twine==4.0.2
    - uri-template==1.2.0
    - urllib3==1.26.15
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - zipp==3.15.0
