name: algo_ops_env
channels:
  - defaults
dependencies:
  - python==3.11.7
  - pip:
    - matplotlib
    - numpy
    - opencv-python-headless
    - ezplotly
    - natsort
    - blosc
    - hatch
    - nose2
    - black