[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "matplotlib",
    "numpy",
    "opencv-python-headless==4.5.4.60",
    'ezplotly',
    'natsort'
]
build-backend = "setuptools.build_meta"